#!/bin/bash

ocat pty,echo=0,raw,link=./serial_out  pty,raw,echo=0,link=./webrtc_momo/serial_in &

cd webrtc_momo

./momo_arm64 --no-audio-device sora --auto wss://node-01.sora-labo.shiguredo.jp/signaling OJIMA-YUKIYA@sora-devtools --role sendonly --multistream true --video-codec-type H264 --video-bit-rate 5000 --metadata '{"signaling_key": "wH_hp6DYomonzVH1eu8mDUN0fgEzmynp6HyXx2HrqUB1v4ds"}'

cd ..

echo "start sora"
